apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy-2022bcd0046
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/library/2022bcd0046-ankur-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"    
            memory: "256Mi"
          limits:
            cpu: "500m" 
            memory: "512Mi"
