apiVersion: v1
kind: Service
metadata:
  name: frontend-service-2022bcd0046
spec:
  type: NodePort
  selector:
    app: frontend
  ports:  
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080